"""paper_scores_and_evidence_version

Revision ID: 554a1d9ff056
Revises: 2ee40bacd748
Create Date: 2026-03-11 20:15:05.481021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '554a1d9ff056'
down_revision: Union[str, None] = '2ee40bacd748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence_store', sa.Column('draft_version', sa.Integer(), nullable=True))
    op.add_column('papers', sa.Column('source_weight', sa.Float(), nullable=True))
    op.add_column('papers', sa.Column('score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'score')
    op.drop_column('papers', 'source_weight')
    op.drop_column('evidence_store', 'draft_version')
    # ### end Alembic commands ###
