"""project_papers

Revision ID: b5708476cd0f
Revises: fcc7f8feb883
Create Date: 2026-03-11 19:38:51.703138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b5708476cd0f'
down_revision: Union[str, None] = 'fcc7f8feb883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_papers',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('paper_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'paper_id')
    )
    op.alter_column('papers', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('papers', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('project_papers')
    # ### end Alembic commands ###
