"""add_query_normalized

Revision ID: fcc7f8feb883
Revises: 1e8819fedd81
Create Date: 2026-03-11 19:30:35.134916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'fcc7f8feb883'
down_revision: Union[str, None] = '1e8819fedd81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_results', sa.Column('query_normalized', sa.Text(), nullable=False))
    op.create_index('ix_search_results_project_query_norm', 'search_results', ['project_id', 'query_normalized'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_search_results_project_query_norm', table_name='search_results')
    op.drop_column('search_results', 'query_normalized')
    # ### end Alembic commands ###
